### ISSUE TITLE
Reference/Target Hardware Platform

### ISSUE THREAD

**Issue by trulede** [dhamstack/AREDNstack#1]
Hello,

do you have some reference or hardware platforms which you are targeting? If someone would want to do some development.

For example: Raspberry PI 4 B and/or Raspberry Pi Zero 2 W as the computer platform and some kind of Radio Hat - so far I could only discover this "CaribouLite RPi HAT" (https://www.crowdsupply.com/cariboulabs/cariboulite-rpi-hat) but I cannot tell if it would be suitable.

Thanks.

**Comment by SensorsIot** [comment]
We mainly target the Raspberry Pi.
But some developments are also targeted to the Mikrotik hAP router (for example some of the phonebook synchronization)
