### ISSUE TITLE
Nerding on about shells and POSIX

### ISSUE THREAD

**Issue by Derisis13** [dhamstack/AREDNstack#3]
Hi!

I decided to take a look at the shell script ChatGPT cooked up for you (mostly from my distrust for AI generated content). The first thing I ran on it was [Shellcheck](https://github.com/koalaman/shellcheck). It's a rich linter for shell that can even be used for GitHub actions for continuous integration. 

To my surprise the script `phonebook_installer.sh` is filled with errors about bash-only features being used. I'm certain that the script works for you (in most cases) and started searching. Eventually I found that Busybox ash (used by OpenWrt) is although a descendant of dash, is expanded from dash (the dialect shellcheck can check the script against) with bash-like features, and this is why your script works. Setting the `--shell=bash` option for shellcheck confirms this as all errors are gone (although some warnings remain that you might want to deal with).

The script is fine as-is for the current OpenWRT release, but you might want to consider making the script fully POSIX-compliant. It would require a rewrite of the parts that shellcheck complains about, but it would allow for wider usage of the script, as the POSIX-defined features should work the same in all shells that implement it (including dash, bash, zsh, etc.). I'm not sure if this'd bring any benefit to the project, but if yes, I'd gladly do it.

**Comment by SensorsIot** [comment]
Thanks for the link. I included the recommendations on this page
